import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { Window } from 'happy-dom';
import { initExperiment, initExperiments } from '../src/lib/experiments.mjs';
import {unitPoints,unitEdges,coverCounts,defaultColors,monoTriangles,lattice,toySpeed} from '../src/lib/math.mjs';
const slugs=fs.readdirSync('dist/discoveries');
function page(slug){const w=new Window({settings:{disableJavaScriptEvaluation:true,disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});w.document.write(fs.readFileSync(slug?`dist/discoveries/${slug}/index.html`:'dist/index.html','utf8'));globalThis.document=w.document;globalThis.window=w;return w;}
test('all original pages link to existing local assets and routes',()=>{assert.equal(slugs.length,10);for(const slug of ['',...slugs]){const w=page(slug),d=w.document;assert.equal(d.querySelectorAll('h1').length,1);assert.ok(d.querySelector('meta[name=description]').content);for(const e of d.querySelectorAll('[href],[src]')){const u=e.getAttribute('href')||e.getAttribute('src');if(!u.startsWith('/ai-math-explainers/'))continue;let p=decodeURIComponent(u.split('#')[0].replace('/ai-math-explainers/',''));if(!p||p.endsWith('/'))p+='index.html';assert.ok(fs.existsSync(path.join('dist',p)),`${slug}: missing ${p}`);}for(const image of d.querySelectorAll('img'))assert.ok(image.alt);w.close();}});
test('independent mathematical invariants',()=>{assert.equal(unitEdges(unitPoints('line')).length,6);assert.equal(unitEdges(unitPoints('hexagon')).length,12);assert.deepEqual(coverCounts([true,true,true]),[2,2,2,2,2]);assert.deepEqual(coverCounts([false,false,false]),[0,0,0,0,0]);assert.equal(monoTriangles(defaultColors()).length,0);assert.equal(monoTriangles(Array(10).fill(0)).length,10);assert.equal(lattice(1).filter(p=>p.kind==='inside').length,1);assert.equal(lattice(1).filter(p=>p.kind==='boundary').length,9);assert.equal(lattice(1.2).filter(p=>p.kind==='inside').length,10);assert.equal(toySpeed(0),0);assert.ok(toySpeed(.999)>998);assert.throws(()=>toySpeed(1),RangeError);});
for(const slug of slugs)test(`${slug}: interactive controls update and reset`,()=>{const w=page(slug),root=w.document.querySelector('[data-experiment]');initExperiment(root);const out=root.querySelector('[data-readout]'),initial=out.textContent;assert.ok(initial.length>20);const modes=root.querySelectorAll('[data-mode]'),range=root.querySelector('[data-range]'),toggle=root.querySelector('[data-toggle]'),loop=root.querySelector('[data-loop]'),edge=root.querySelector('[data-edge]');if(modes.length){[...modes].find(e=>e.getAttribute('aria-pressed')!=='true').click();}else if(range){range.value=slug==='lattice-volume'?'120':range.max;range.dispatchEvent(new w.Event('input'));}else if(toggle){toggle.checked=!toggle.checked;toggle.dispatchEvent(new w.Event('input'));}else if(loop){loop.checked=false;loop.dispatchEvent(new w.Event('input'));}else if(edge){edge.click();}assert.notEqual(out.textContent,initial);if(slug==='lattice-volume')assert.match(out.textContent,/10 interior/);if(slug==='cycle-double-cover')assert.match(out.textContent,/1, 1, 2, 2, 1/);if(slug==='matrix-multiplication')assert.equal(root.querySelectorAll('.missing').length,1);if(slug==='riemann-bound')assert.equal(root.querySelector('.proportion span').style.width,'41.6%');root.querySelector('[data-reset]').click();assert.equal(out.textContent,initial);if(toggle&&range){toggle.checked=!toggle.checked;toggle.dispatchEvent(new w.Event('input'));assert.notEqual(out.textContent,initial);}w.close();});
test('optional agent readout shares visible state and rejects invalid arguments',()=>{const w=page('cycle-double-cover');let tool;Object.defineProperty(w.document,'modelContext',{value:{registerTool(t){tool=t;}}});initExperiments();assert.equal(tool.name,'read_math_experiment');assert.equal(tool.execute({}).result,w.document.querySelector('[data-readout]').textContent);assert.throws(()=>tool.execute({unknown:true}));w.close();});

test('each authored story has a complete route, sources and a gated entry link',()=>{
 const files=fs.readdirSync('src/content/stories').filter(f=>f.endsWith('.md'));
 assert.equal(files.length,10,'All ten companion narratives must exist');
 for(const slug of slugs){const w=page(slug),link=w.document.querySelector('.story-invitation');assert.equal(Boolean(link),files.includes(slug+'.md'));w.close();}
 for(const f of files){const slug=f.slice(0,-3),w=new Window();w.document.write(fs.readFileSync(`dist/discoveries/${slug}/story/index.html`,'utf8'));const d=w.document;
 assert.equal(d.querySelectorAll('h1').length,1);const words=d.querySelector('.story-prose').textContent.trim().split(/\s+/).length;assert.ok(words>=900&&words<=1400,`Narrative has ${words} words`);
 assert.ok(d.querySelectorAll('.story-timeline li').length>=3);assert.ok(d.querySelectorAll('.story-reading li').length>=4);assert.ok(d.querySelector('time[datetime]'));
 for(const link of d.querySelectorAll('a[href]')){const u=link.getAttribute('href');if(!u.startsWith('/ai-math-explainers/'))continue;let target=u.split('#')[0].replace('/ai-math-explainers/','');if(!target||target.endsWith('/'))target+='index.html';assert.ok(fs.existsSync(path.join('dist',target)),u);}
 assert.ok(d.querySelector('.story-return'));const steps=d.querySelectorAll('.story-timeline li');assert.ok(steps.length<=6);assert.ok(d.querySelectorAll('.story-reading li').length<=6);const nav=d.querySelectorAll('nav[aria-label="Companion stories"] a');assert.ok(nav.length>=1&&nav.length<=2);w.close();}
});
